test
Buherchuk/babuherchuk pull request #1
Opened 2022-12-12 09:51 UTC by Buherchuk

2022-12-14 13:01 UTC, adudyak requested changes

2022-12-14 13:01 UTC, adudyak commented on tests/store_test.js
> +    pause();
remove pause

2022-12-14 13:01 UTC, adudyak commented on tests/store_test.js
> +    registerPage.fillRegisxtrationDetails(registrationUser);
spelling issue in method's name

2022-12-14 13:01 UTC, adudyak commented on pages/register.js
> +    I.grabTextFrom(this.successRegistrationText);
you don't need to grab header text, verify successful registration text in separate method instead

2022-12-15 16:17 UTC, Buherchuk commented on tests/store_test.js
> +    pause();
Done

2022-12-15 16:20 UTC, Buherchuk commented on tests/store_test.js
> +    registerPage.fillRegisxtrationDetails(registrationUser);
Done

2022-12-15 20:09 UTC, closed without merging